<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="19427" started-at="2020-11-30T10:03:04 EST" finished-at="2020-11-30T10:03:23 EST">
    <groups>
    </groups>
    <test name="Functional-chrome" duration-ms="9854" started-at="2020-11-30T10:03:04 EST" finished-at="2020-11-30T10:03:14 EST">
      <class name="com.vndly.testCases.TC001_Student_RegistrationForm">
        <test-method status="PASS" signature="beforeClass(java.lang.String)[pri:0, instance:com.vndly.testCases.TC001_Student_RegistrationForm@18bf3d14]" name="beforeClass" is-config="true" duration-ms="8176" started-at="2020-11-30T10:03:04 EST" finished-at="2020-11-30T10:03:12 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC_fill_Student_RegistrationForm()[pri:1, instance:com.vndly.testCases.TC001_Student_RegistrationForm@18bf3d14]" name="TC_fill_Student_RegistrationForm" duration-ms="471" started-at="2020-11-30T10:03:12 EST" finished-at="2020-11-30T10:03:13 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_fill_Student_RegistrationForm -->
        <test-method status="PASS" signature="validateText()[pri:2, instance:com.vndly.testCases.TC001_Student_RegistrationForm@18bf3d14]" name="validateText" duration-ms="41" started-at="2020-11-30T10:03:13 EST" finished-at="2020-11-30T10:03:13 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateText -->
        <test-method status="FAIL" signature="unValidedText_Capture_A_Screenshot()[pri:3, instance:com.vndly.testCases.TC001_Student_RegistrationForm@18bf3d14]" name="unValidedText_Capture_A_Screenshot" duration-ms="26" started-at="2020-11-30T10:03:13 EST" finished-at="2020-11-30T10:03:13 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thanks for submitting the formA] but found [Thanks for submitting the form]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thanks for submitting the formA] but found [Thanks for submitting the form]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vndly.testCases.TC001_Student_RegistrationForm.unValidedText_Capture_A_Screenshot(TC001_Student_RegistrationForm.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unValidedText_Capture_A_Screenshot -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.vndly.testCases.TC001_Student_RegistrationForm@18bf3d14]" name="afterClass" is-config="true" duration-ms="640" started-at="2020-11-30T10:03:13 EST" finished-at="2020-11-30T10:03:14 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.vndly.testCases.TC001_Student_RegistrationForm -->
    </test> <!-- Functional-chrome -->
    <test name="Functional-edge" duration-ms="9317" started-at="2020-11-30T10:03:14 EST" finished-at="2020-11-30T10:03:23 EST">
      <class name="com.vndly.testCases.TC001_Student_RegistrationForm">
        <test-method status="PASS" signature="beforeClass(java.lang.String)[pri:0, instance:com.vndly.testCases.TC001_Student_RegistrationForm@727803de]" name="beforeClass" is-config="true" duration-ms="7299" started-at="2020-11-30T10:03:14 EST" finished-at="2020-11-30T10:03:21 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC_fill_Student_RegistrationForm()[pri:1, instance:com.vndly.testCases.TC001_Student_RegistrationForm@727803de]" name="TC_fill_Student_RegistrationForm" duration-ms="388" started-at="2020-11-30T10:03:21 EST" finished-at="2020-11-30T10:03:22 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_fill_Student_RegistrationForm -->
        <test-method status="PASS" signature="validateText()[pri:2, instance:com.vndly.testCases.TC001_Student_RegistrationForm@727803de]" name="validateText" duration-ms="28" started-at="2020-11-30T10:03:22 EST" finished-at="2020-11-30T10:03:22 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateText -->
        <test-method status="FAIL" signature="unValidedText_Capture_A_Screenshot()[pri:3, instance:com.vndly.testCases.TC001_Student_RegistrationForm@727803de]" name="unValidedText_Capture_A_Screenshot" duration-ms="24" started-at="2020-11-30T10:03:22 EST" finished-at="2020-11-30T10:03:22 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thanks for submitting the formA] but found [Thanks for submitting the form]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thanks for submitting the formA] but found [Thanks for submitting the form]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vndly.testCases.TC001_Student_RegistrationForm.unValidedText_Capture_A_Screenshot(TC001_Student_RegistrationForm.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unValidedText_Capture_A_Screenshot -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.vndly.testCases.TC001_Student_RegistrationForm@727803de]" name="afterClass" is-config="true" duration-ms="1108" started-at="2020-11-30T10:03:22 EST" finished-at="2020-11-30T10:03:23 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.vndly.testCases.TC001_Student_RegistrationForm -->
    </test> <!-- Functional-edge -->
  </suite> <!-- Suite -->
</testng-results>
